Add `priority` field to loaded resources for fine-grinded load ordering
Liquipedia/ResourceLoaderArticles pull request #9
Opened 2024-04-13 14:48 UTC by iMarbot

## Summary

As discussed previously in the Lua & Commons Resources repo, adding priority field to RLA extension so that we can order them based on more than just alphabetical order.

Also disabled editing the form fields on the delete form.

## How did you test this change?

Untested as I don't have a test wiki. Please test before merging.

2024-04-13 14:52 UTC, FO-nTTaX commented on sql/resourceloaderarticlesPriorityMigration.sql
> +ALTER TABLE resourceloaderarticles
```suggestion
ALTER TABLE /*_*/resourceloaderarticles
``` This adds the correct table prefix

2024-04-13 14:59 UTC, hjpalpha reviewed
just something to be aware of:
not sure if desc sort order is the most intuitive
i think arguments can be made for both sort orders
hence imo adding some information on the special page about how the prio works would be a good idea

2024-04-13 15:25 UTC, hjpalpha reviewed
apart from the sorting question lgtm
mind i am on phone

2024-04-13 15:25 UTC, hjpalpha commented on src/SpecialPage/SpecialResourceLoaderArticles.php
> +			[ 'ORDER BY' => 'rla_priority DESC, rla_type ASC, rla_page ASC, rla_wiki ASC' ]
wouldn't using prio before type change loading order compared to now?

2024-04-13 16:30 UTC, hjpalpha approved these changes
lgtm on phone

2024-04-15 14:37 UTC, FO-nTTaX requested changes

2024-04-15 14:37 UTC, FO-nTTaX commented on src/SpecialPage/SpecialResourceLoaderArticles.php
> +				'help' => $this->msg( 'resourceloaderarticles-help-priority' )->text(),
```suggestion
				'help-message' => 'resourceloaderarticles-help-priority' ),
```

2024-04-15 14:37 UTC, FO-nTTaX commented on src/SpecialPage/SpecialResourceLoaderArticles.php
> +				'help' => $this->msg( 'resourceloaderarticles-help-priority' )->text(),
```suggestion
				'help-message' => 'resourceloaderarticles-help-priority',
```

2024-04-15 14:37 UTC, FO-nTTaX commented on src/SpecialPage/SpecialResourceLoaderArticles.php
> +				'help' => $this->msg( 'resourceloaderarticles-help-priority' )->text(),
```suggestion
				'help-message' => 'resourceloaderarticles-help-priority',
```

2024-04-15 14:37 UTC, FO-nTTaX commented on sql/resourceloaderarticlesPriorityMigration.sql
> +  ADD COLUMN IF NOT EXISTS `rla_priority` int(11) NOT NULL;
```suggestion
  ADD COLUMN IF NOT EXISTS `rla_priority` int(11) NOT NULL;
 UPDATE /*_*/resourceloaderarticles SET `rla_priority` = 100;
```
What do we want the default value to be? I set 100 here, but we should make a decision.

2024-04-15 14:38 UTC, FO-nTTaX commented on sql/resourceloaderarticlesPriorityMigration.sql
> +  ADD COLUMN IF NOT EXISTS `rla_priority` int(11) NOT NULL;
This is to set a value for the already existing rows in the table.

2024-04-15 14:52 UTC, FO-nTTaX commented
> Idk how I didn't see `help-message` in HTMLForm 🤦

That's why we have code review :P

2024-04-15 14:53 UTC, FO-nTTaX commented on sql/resourceloaderarticlesPriorityMigration.sql
> +  ADD COLUMN IF NOT EXISTS `rla_priority` int(11) NOT NULL;
that's also fine, but I'd like to have it in the migration explicitly

2024-04-15 15:05 UTC, FO-nTTaX commented on src/SpecialPage/SpecialResourceLoaderArticles.php
> +				'help-message' => 'resourceloaderarticles-help-priority' ),
stray closing parentheses

2024-04-15 19:47 UTC, FO-nTTaX commented on sql/resourceloaderarticlesPriorityMigration.sql
> + UPDATE /*_*/resourceloaderarticles SET `rla_priority` = 100;
I have no hard feelings either way, 0 is fine with me

2024-04-16 13:45 UTC, FO-nTTaX approved these changes

2024-04-16 13:46 UTC, merged